#!/usr/bin/env python3
"""Calculate stock returns from price data and generate a markdown backtest report."""
import argparse
import json
from datetime import datetime


def calc_return(open_price, close_price):
    return (close_price - open_price) / open_price * 100


def load_data(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def render_report(data, output_path):
    stocks = data.get('stocks', [])
    start_date = data.get('start_date', '')
    end_date = data.get('end_date', '')

    for s in stocks:
        s['return'] = calc_return(s['open'], s['close'])

    stocks.sort(key=lambda x: x['return'], reverse=True)

    lines = [
        f"# {start_date}-{end_date} 信号选股回测结果\n",
        "> 统计口径：起始日开盘价 → 结束日收盘价\n\n",
        "| 排名 | 标的 | 代码 | 开盘价 | 收盘价 | 区间收益 |\n",
        "|:----:|:----:|:----:|:------:|:------:|:--------:|\n",
    ]

    for i, s in enumerate(stocks, 1):
        lines.append(f"| {i} | {s['name']} | {s['code']} | {s['open']:.2f} | {s['close']:.2f} | {s['return']:+.2f}% |\n")

    lines.append("\n## 收益统计\n\n")
    if stocks:
        returns = [s['return'] for s in stocks]
        lines.append(f"- 平均收益：{sum(returns)/len(returns):+.2f}%\n")
        lines.append(f"- 最高收益：{max(returns):+.2f}%\n")
        lines.append(f"- 最低收益：{min(returns):+.2f}%\n")

    lines.append("\n---\n\n*Generated by backtest-signal-stocks skill.*\n")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)

    print(f"Report written to {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Calculate backtest returns and generate report')
    parser.add_argument('--input', required=True, help='Input JSON file with prices')
    parser.add_argument('--output', required=True, help='Output markdown report path')
    args = parser.parse_args()

    data = load_data(args.input)
    render_report(data, args.output)


if __name__ == '__main__':
    main()
